import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { 
  Users, 
  MessageSquare, 
  Database, 
  Clock, 
  Mail, 
  Phone, 
  FileText, 
  Lock, 
  Copy, 
  Check, 
  AlertCircle, 
  Server,
  RefreshCw,
  LogOut
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { 
  getCurrentUser, 
  getAllUsers, 
  getContactSubmissions, 
  isMock, 
  signOut,
  type UserProfile, 
  type ContactSubmission 
} from "@/lib/supabase";
import { toast } from "sonner";

export const Route = createFileRoute("/dashboard")({
  component: DashboardPage,
});

function DashboardPage() {
  const navigate = useNavigate();
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [inquiries, setInquiries] = useState<ContactSubmission[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  const sqlSchema = `-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Create contact submissions table
CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts into contact submissions" ON public.contact_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin read access to contact submissions" ON public.contact_submissions FOR SELECT USING (true);

-- Trigger to automatically create profiles when auth user registers
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'User'),
    new.email
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();`;

  const copySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    toast.success("SQL Schema copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const loadData = async () => {
    setLoading(true);
    try {
      const u = await getAllUsers();
      const i = await getContactSubmissions();
      setUsers(u);
      setInquiries(i);
    } catch (err: any) {
      toast.error(err.message || "Failed to fetch dashboard data");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    getCurrentUser().then((user) => {
      if (!user) {
        setAuthChecked(true);
        setLoading(false);
        return;
      }
      setCurrentUser(user);
      setAuthChecked(true);
      loadData();
    });
  }, []);

  const handleLogout = async () => {
    try {
      await signOut();
      toast.success("Logged out successfully");
      navigate({ to: "/login" });
    } catch (error: any) {
      toast.error(error.message || "Failed to sign out");
    }
  };

  if (authChecked && !currentUser) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center bg-background px-4">
        <Card className="max-w-md w-full border border-border shadow-soft text-center p-8">
          <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-primary/10 text-primary mb-4">
            <Lock className="h-6 w-6" />
          </div>
          <CardTitle className="text-2xl font-semibold">Access Restricted</CardTitle>
          <CardDescription className="mt-2">
            Please sign in to view the owner's dashboard and manage user accounts and inquiries.
          </CardDescription>
          <div className="mt-6 flex flex-col gap-3">
            <Link to="/login">
              <Button className="w-full bg-primary hover:bg-primary/90 h-10">Sign In Now</Button>
            </Link>
            <Link to="/">
              <Button variant="outline" className="w-full h-10">Back to Homepage</Button>
            </Link>
          </div>
        </Card>
      </div>
    );
  }

  if (loading && !currentUser) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-2">
          <RefreshCw className="h-8 w-8 text-primary animate-spin" />
          <p className="text-sm text-muted-foreground">Verifying access...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container-x py-8 min-h-[calc(100vh-4rem)]">
      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border pb-6">
        <div>
          <span className="text-sm font-medium text-primary uppercase tracking-wider">Administration</span>
          <h1 className="text-3xl font-semibold mt-1">Owner's Dashboard</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Logged in as <span className="font-semibold text-foreground">{currentUser?.email}</span>
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={loadData} disabled={loading} className="gap-1.5">
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
          <Button variant="destructive" size="sm" onClick={handleLogout} className="gap-1.5">
            <LogOut className="h-4 w-4" />
            Sign Out
          </Button>
        </div>
      </div>

      {/* DATABASE CONNECTION STATUS */}
      <div className="mt-6">
        {isMock ? (
          <Card className="border border-amber-500/30 bg-amber-500/5 shadow-soft rounded-2xl">
            <CardContent className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 p-5">
              <div className="flex gap-3">
                <AlertCircle className="h-6 w-6 text-amber-600 shrink-0 mt-0.5 md:mt-0" />
                <div>
                  <h4 className="font-semibold text-amber-800 dark:text-amber-400">LocalStorage Simulation Mode</h4>
                  <p className="text-sm text-amber-700/80 dark:text-amber-400/80 mt-1 max-w-2xl">
                    The app is running in simulation mode using local storage because Supabase environment variables are missing. All signups, logins, and contact submissions will work perfectly on this browser.
                  </p>
                </div>
              </div>
              <div className="text-xs bg-amber-500/10 text-amber-800 dark:text-amber-400 border border-amber-500/20 px-3 py-1.5 rounded-lg shrink-0 font-medium">
                Simulation Active
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card className="border border-emerald-500/30 bg-emerald-500/5 shadow-soft rounded-2xl">
            <CardContent className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 p-5">
              <div className="flex gap-3">
                <Server className="h-6 w-6 text-emerald-600 shrink-0 mt-0.5 md:mt-0" />
                <div>
                  <h4 className="font-semibold text-emerald-800 dark:text-emerald-400">Supabase Connected (Live)</h4>
                  <p className="text-sm text-emerald-700/80 dark:text-emerald-400/80 mt-1 max-w-2xl">
                    Your website is successfully connected to your live Supabase project. Credentials, profiles, and contact submissions are synchronized with the secure cloud database.
                  </p>
                </div>
              </div>
              <div className="text-xs bg-emerald-500/10 text-emerald-800 dark:text-emerald-400 border border-emerald-500/20 px-3 py-1.5 rounded-lg shrink-0 font-medium">
                Supabase Live
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      {/* ANALYTICS STRIP */}
      <div className="grid gap-6 mt-6 sm:grid-cols-3">
        <Card className="bg-card border border-border rounded-2xl shadow-soft">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Inquiries</CardTitle>
            <MessageSquare className="h-5 w-5 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{inquiries.length}</div>
            <p className="text-xs text-muted-foreground mt-1">Contact form submissions</p>
          </CardContent>
        </Card>

        <Card className="bg-card border border-border rounded-2xl shadow-soft">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Registered Users</CardTitle>
            <Users className="h-5 w-5 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{users.length}</div>
            <p className="text-xs text-muted-foreground mt-1">User profiles created</p>
          </CardContent>
        </Card>

        <Card className="bg-card border border-border rounded-2xl shadow-soft">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Database Sync</CardTitle>
            <Database className="h-5 w-5 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-lg font-semibold">{isMock ? "LocalStorage" : "Supabase Live"}</div>
            <p className="text-xs text-muted-foreground mt-1">Current active data store</p>
          </CardContent>
        </Card>
      </div>

      {/* MAIN DATA TABLES */}
      <Tabs defaultValue="inquiries" className="w-full mt-8">
        <TabsList className="flex w-full md:w-auto md:inline-flex bg-muted p-1 rounded-xl border border-border gap-1 mb-4">
          <TabsTrigger value="inquiries" className="rounded-lg font-medium text-sm transition-all px-6 py-2">
            Contact Inquiries ({inquiries.length})
          </TabsTrigger>
          <TabsTrigger value="users" className="rounded-lg font-medium text-sm transition-all px-6 py-2">
            Registered Users ({users.length})
          </TabsTrigger>
          <TabsTrigger value="supabase" className="rounded-lg font-medium text-sm transition-all px-6 py-2">
            Supabase Setup
          </TabsTrigger>
        </TabsList>

        {/* CONTACT INQUIRIES TAB */}
        <TabsContent value="inquiries" className="bg-card border border-border rounded-2xl shadow-soft overflow-hidden mt-0">
          <div className="p-6 border-b border-border">
            <h3 className="font-semibold text-lg text-foreground">Inquiries Log</h3>
            <p className="text-sm text-muted-foreground mt-0.5">Contact form submissions received from prospects</p>
          </div>
          
          {inquiries.length === 0 ? (
            <div className="p-12 text-center text-muted-foreground">
              <MessageSquare className="mx-auto h-12 w-12 opacity-30 mb-3" />
              <p className="font-medium text-foreground">No inquiries found</p>
              <p className="text-sm mt-1">Inquiries submitted on the homepage contact form will show up here.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="w-[180px]">Name</TableHead>
                    <TableHead className="w-[220px]">Contact Info</TableHead>
                    <TableHead>Message</TableHead>
                    <TableHead className="w-[180px] text-right">Submitted Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {inquiries.map((inquiry) => (
                    <TableRow key={inquiry.id} className="hover:bg-accent/30 transition-colors">
                      <TableCell className="font-medium align-top">{inquiry.name}</TableCell>
                      <TableCell className="align-top space-y-1">
                        <div className="flex items-center gap-1.5 text-sm">
                          <Mail className="h-3.5 w-3.5 text-muted-foreground" />
                          <a href={`mailto:${inquiry.email}`} className="hover:text-primary hover:underline">{inquiry.email}</a>
                        </div>
                        {inquiry.phone && (
                          <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                            <Phone className="h-3.5 w-3.5" />
                            <a href={`tel:${inquiry.phone}`} className="hover:text-primary hover:underline">{inquiry.phone}</a>
                          </div>
                        )}
                      </TableCell>
                      <TableCell className="align-top text-foreground/90 max-w-md whitespace-pre-wrap">
                        {inquiry.message}
                      </TableCell>
                      <TableCell className="align-top text-right text-muted-foreground text-sm">
                        <div className="flex items-center justify-end gap-1.5">
                          <Clock className="h-3.5 w-3.5" />
                          {new Date(inquiry.created_at).toLocaleDateString(undefined, {
                            month: "short",
                            day: "numeric",
                            year: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </TabsContent>

        {/* REGISTERED USERS TAB */}
        <TabsContent value="users" className="bg-card border border-border rounded-2xl shadow-soft overflow-hidden mt-0">
          <div className="p-6 border-b border-border">
            <h3 className="font-semibold text-lg text-foreground">Registered Users</h3>
            <p className="text-sm text-muted-foreground mt-0.5">Accounts created by users (including names, emails, and passwords inside Supabase)</p>
          </div>

          {users.length === 0 ? (
            <div className="p-12 text-center text-muted-foreground">
              <Users className="mx-auto h-12 w-12 opacity-30 mb-3" />
              <p className="font-medium text-foreground">No registered users</p>
              <p className="text-sm mt-1">When users sign up using the Login/Register page, they will show up here.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>User ID</TableHead>
                    <TableHead>Name</TableHead>
                    <TableHead>Email Address</TableHead>
                    <TableHead className="text-right">Joined Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {users.map((u) => (
                    <TableRow key={u.id} className="hover:bg-accent/30 transition-colors">
                      <TableCell className="font-mono text-xs text-muted-foreground max-w-[120px] truncate">{u.id}</TableCell>
                      <TableCell className="font-medium">{u.name}</TableCell>
                      <TableCell>
                        <a href={`mailto:${u.email}`} className="hover:text-primary hover:underline">{u.email}</a>
                      </TableCell>
                      <TableCell className="text-right text-muted-foreground text-sm">
                        {new Date(u.created_at).toLocaleDateString(undefined, {
                          month: "short",
                          day: "numeric",
                          year: "numeric",
                        })}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </TabsContent>

        {/* SUPABASE SETUP INSTRUCTIONS TAB */}
        <TabsContent value="supabase" className="bg-card border border-border rounded-2xl shadow-soft p-6 mt-0">
          <div>
            <h3 className="font-semibold text-lg text-foreground flex items-center gap-2">
              <Server className="h-5 w-5 text-primary" />
              Supabase Configuration Guide
            </h3>
            <p className="text-sm text-muted-foreground mt-1">
              To connect your live database and authenticate actual users, follow these instructions.
            </p>
          </div>

          <div className="mt-6 space-y-6">
            <div>
              <h4 className="font-semibold text-sm text-foreground flex items-center gap-2">
                <span className="grid place-items-center h-5 w-5 bg-primary/10 text-primary text-xs rounded-full font-bold">1</span>
                Create database tables
              </h4>
              <p className="text-sm text-muted-foreground mt-1">
                Go to your <strong>Supabase Dashboard &gt; SQL Editor</strong>, create a new query, paste the script below, and click <strong>Run</strong>.
              </p>
              
              <div className="relative mt-3">
                <button 
                  onClick={copySql}
                  className="absolute right-3 top-3 p-1.5 rounded bg-background hover:bg-accent border border-border transition-colors text-muted-foreground hover:text-foreground"
                  title="Copy SQL Schema"
                >
                  {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                </button>
                <pre className="p-4 bg-muted text-xs rounded-xl overflow-x-auto text-foreground/80 border border-border font-mono max-h-[300px]">
                  {sqlSchema}
                </pre>
              </div>
            </div>

            <div className="border-t border-border pt-6">
              <h4 className="font-semibold text-sm text-foreground flex items-center gap-2">
                <span className="grid place-items-center h-5 w-5 bg-primary/10 text-primary text-xs rounded-full font-bold">2</span>
                Set Environment Variables
              </h4>
              <p className="text-sm text-muted-foreground mt-1">
                Create a <code>.env</code> file in your project's root folder and append your Supabase Keys (available in <strong>Project Settings &gt; API</strong>):
              </p>
              <pre className="p-4 bg-muted text-xs rounded-xl text-foreground/80 border border-border font-mono mt-3">
                VITE_SUPABASE_URL=your-supabase-project-url{"\n"}
                VITE_SUPABASE_ANON_KEY=your-supabase-anon-key
              </pre>
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
